### ISSUE TITLE
US#01-Overview-Page

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#1]
## Value proposition
As a user 
I want to see an overview of all existing DIY Projects, 
In order to find some inspiration and get an overview of the DIY Projects.
## Description
![Image](https://github.com/On-Fi/DIY-App/assets/149980693/b36edea3-0114-45fd-80d1-71f76aefe97c)
- The overview page lists all existing DIY Projects
in Project Cards containing the project title, 
amount of time needed and price category.
## Acceptance criteria
- [x] There is a header in the top,
   that sticks to the screen when scrolling
- [x] a list of all DIY Project is displayed
- [x] for every DIY Project, 
  there is a card that contains the title, 
  the amount of time needed, price category, 
  category and difficulty level
## Tasks
- [x] set up a MongoDB database
- [x] add DIY Project data to MongoDB database
- [x] create a api Folder + GET-Route 
- [x] create mongoose connect file and a Model file
- [x] set up a GET Request
- [x] set up index.js-Page
- [x] create Header Component
- [x] create Card Component
- [x] create Card List Component
- [x] map the data in the Card Components

**Comment by F-Kirchhoff** [comment]
Hey DIY Team, 
very good user story! there are only minor things to consider:
- please add to the acceptance criteria that a list of DIY Cards is displayed
- you are missing the mongoose connect and Model files for accessing the mongoDB
- you might want to add a task "add dummy data to mongoDB database"

Otherise its ready to go!
