### ISSUE TITLE
US#09-My-Projects/Profile Page

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#10]
## Value proposition
As a user
I want to have a profile page
so that I can access the user-related features from there (personal information, login/logout, my profile, favorites)

## Description

![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/5157c2d2-db6a-4373-80b9-4a658254adfe)

## Acceptance criteria
- [x] there are two new pages: /profile and /profile/my-projects
- [x] when the user is not logged in: on the page /profile there is a short description, a login button and a link to the favorites page
- [x] when the user **is** logged in: on the page /profile there is the image of the user, the username, a link to /my-projects, a link to the favorites page and a logout button
- [x] the profile/my-projects page shows all projects, that the current user has created (is author)
- [x] additionally there is a delete and an edit button on every card in the /my-projects-page

## Tasks
- [x] set up the page /profile
- [x] get session data on /profile
- [x] render content conditionally, depending if there is a session or not
- [x] create /my-projects page
- [x] write a function that looks for only those projects, that the current user has created (is author)
- [x] render cards + edit/delete button

**Comment by F-Kirchhoff** [comment]
Hey DIY Team!

It does not really become clear from the AC that you mainly talk about the pofile page. Please clarify the section. 

I think it is a bit odd to show a favorites page when the user is not logged in. Favorites are something that is generally tied to a specific user. 

The My projects section should be displayed on the profile page. There you can render them with the additional action buttons.

**Comment by kristinwegener** [comment]
Hi Felix, thank you for your review :)

we would like to keep the favorites page available for not-logged-in users, because it is currently implemented via local storage. If we want it to be connected with the user profile in the database that would be a completely new task and would be too big for this user story. If we enable the favorites feature only for logged-in-users we would take away a feature from not-logged-in-users that they **could** have technically.
Later on we want to link the favorites to the user profile (draft: https://github.com/On-Fi/D.I.Y-App/issues/25). Is that fine for you?

We'll update the rest :) Thank you!

**Comment by Roland-Hufnagel** [comment]
It's fine and clear to me 👍
