### ISSUE TITLE
US#10-Project-Images

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#11]
## Value proposition
As a user
I want to see images for each project
In order to get a better idea of the resulting end product

## Description
![Image](https://github.com/On-Fi/DIY-App/assets/149980693/de8f1188-a897-44dd-992e-2841ea6b6e68)
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/33d12bb2-da96-4d1e-82c5-2bfe31e8d72c)
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/a60ee575-4db1-45ec-8341-bc301377ad71)

## Acceptance criteria
- [x] Every Project has an image
- [x] The image is displayed on the overview screen as well as the detail page of every project
- [x] In the create-project-form there is a new input field for image upload
- [x] If there has not been uploaded an image yet a default image is displayed

## Tasks
- [x] integrate Cloudinary
- [x] set up a pre-set
- [x] POST Request for image upload
- [x] save new image in MongoDB Database
- [x] add upload field to form component
- [x] edit card component and detail pages to display images
