### ISSUE TITLE
US#11-Step-by-Step-Instructions

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#14]
## Value proposition
As a user
I want to be able to create the project instructions in a step-by-step format
so that it is easier to explain the instructions to other users.

As a user
I want to see project instructions in a step-by-step format
so that it is easier for me to follow the instructions while crafting.

## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/340a38c7-5769-41eb-a960-a865f8ecc32c)
In the new-project-form there is initially one text field for the instructions. When clicking the button "add more steps" another text field appears etc.
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/120f0f22-7f73-4a8b-869f-8ce8cd0c8ff3)
In the detail page for every project the instructions are displayed step by step, each prefixed with the number of the step (1,2,3...)
## Acceptance criteria
- [x] Initially there is one text input for the instructions
- [x] there is a button "add more steps"
- [x] when clicking this button another text input for instructions appears
- [x] the first input is labeled with 1, the second with 2 etc.
## Tasks
- [ ] install React Form Hook
- [x] implement behavior for text input (new text input appears when clicking the button)
- [x] update the project model
- [x] update example data in MongoDB
- [x] update the return statement of the details page (to show all instruction steps)

**Comment by Hendrik-Pils** [comment]
Hey, very nice User Story so far, but I have some suggestions:
- You could make it clear in the value proposition, that you want to:
  1. Make sure the user has the option to enter new steps for the projects (edit project steps)
  2. Have the steps then be displayed in the detail page (a different page)
 
- Also you could specify in the tasks, what behavior the text input should have.

**Comment by CJAkkuec** [comment]
Looks good, no notes 🚀
