### ISSUE TITLE
US#12-Multiple tools and material

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#15]
## Value proposition
As a user
I want to be able to save multiple tools and material
so that I can enter the amount for every tool and material individually
## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/749a536b-7373-4a01-93c2-4cad25c921cc) 
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/137a978e-1770-4564-b920-5e7f230c6027)

## Acceptance criteria
 - [x] In the new-project-form there is initially one field for tools and two fields for material (one for the amount, one for the tool)
 - [x] When clicking the button "add more tools" or "add more material" another text field appears
 - [x] in case of material two fields appear: one for amount, one for the name of the tool)
 - [x] On the details page the tools and material are displayed in rows. Each tool is listed with bullet points and for each material the amount is displayed.

## Tasks
 - [x] Change example data in MongoDB (arrays instead of strings)
 - [x] edit schema for projects model
 - [ ] install react form hook
 - [x] create button to add additional fields for tools/material
 - [ ] use react-form-hook to implement logic (new field appears for every click)
 - [x] split material input into two inputs (amount & tool name)
 - [x] on details page edit rendering of tools & material (map over the tools/material array)

**Comment by F-Kirchhoff** [comment]
Hey DIY Team,
please add some more information to the tasks and try to describe how you need to edit the fields. Everything else looks great!

**Comment by F-Kirchhoff** [comment]
LGTM
