### ISSUE TITLE
US#14 - Delete project

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#18]
## Value proposition
As a user
I want to delete projects
so that I can delete e.g. duplicates, old projects etc.

## Description

![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/fedaabc5-8280-4211-90a9-d75fe5962118)

## Acceptance criteria
- [x] There is a button "Delete project" on every detail page
- [x] when clicking this button the user is asked to confirm the deletion
- [x] On this confirm-pop-up the user can cancel the deletion (and get back to the details page) or confirm the deletion
- [x] After deletion the user is redirected to the overview page
- [x] The deleted project is not displayed on the overview page anymore

## Tasks
- [x] create new DELETE route in api folder
- [x] integrate new button on details page
- [x] write new handler function for deletion
- [x] integrate pop-up

**Comment by CJAkkuec** [comment]
Perfect ✨
