### ISSUE TITLE
US#02-Create-A-New-Project-Page

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#2]
## Value proposition
As a user 
I want to create new DIY Projects,
In order to digitize my creative ideas.
## Description
![Image](https://github.com/On-Fi/DIY-App/assets/149980693/3e0ec4c1-4b2c-4ea0-a22a-57333d49c850)
- The create-Form asks users for information
about their DIY project such as title, category,
amount of time needed, difficulty level,
equipment/tools and the instructions. After entering
all data the users can submit their project 
or cancel the process.
## Acceptance criteria
- [x] The form has the following fields: 
  title, category, difficulty level,
  duration, tools, materials, instructions
- [x] Clicking the button "Save" saves the new DIY project
  and adds it to the overview list and redirects the user
  to the overview page.
- [x] Clicking the button "Cancel" redirects the user to the
  overview page.
- [x] On the Overview page there is a navigation bar. The navigation bar
   is always visible (also when scrolling)
- [x] Clicking the button + redirects the user
  to the create-Form page
- [x] Clicking the button "home" redirects the user to the home page
## Tasks
- [x] create Navigation Component (make it sticky)
- [x] create Form Component 
- [x] set up a Model
- [x] create api folder
- [x] create POST Route
- [x] create a submit handler that triggers a POST Request

**Comment by Janis1992-08** [comment]
Looks good, but isn't that a bit much for a single user story?
