### ISSUE TITLE
US#15 - Change styling

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#24]
## Value proposition
As a user
I want a nice styling of the app
so it's more fun to browse through the projects

## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/9c60dc2d-3f13-46ce-852c-29ea388469d8)
The styling of the app is similar to this Figma Design

## Acceptance criteria
- [ ] On all pages (overview, detail, form, favorites) the design above is implemented (doesn't have to be 100% the same, but similar)

## Tasks
- [x] import new font
- [x] import logo
- [x] import icons if necessary
- [ ] write global variables for colors
- [x] (if necessary write new components for e.g. reusable button)
- [x] adjust css on (probably) all components and pages

**Comment by marcbendixen** [comment]
LGTM 🚀
