### ISSUE TITLE
US#18 - Show popularity of projects

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#25]
## Value proposition
As a user
I want to see how many people have already favorited a project
to see how popular a project is.

## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/bc29a743-a946-421a-8af2-f3d6b6a3a81c)

## Acceptance criteria
- [ ] On every detail page, below the heart icon the amount of users who have favorited the project is displayed
- [ ] Below the instructions there is a text box which shows text based on this amount (see wireframe)

## Tasks
- [ ] save favorites in database (in user)
- [ ] fetch user data
- [ ] count amount of favorites/project and render text accordingly
