### ISSUE TITLE
US#19 - Check accessibility

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#26]
## Value proposition
As any user
I want to be able to consume all content of the woodworm app regardless of any disabilities etc.
in order to not be excluded

## Description
We want woodworm🐛 to be inclusive and for everybody

## Acceptance criteria
- [ ] the whole page is accessible to everyone

## Tasks
- [ ] we use semantic HTML tags where possible
- [x] we use ARIA roles, labels, labelledby etc. where necessary
- [x] we optimize accessibility of the forms (for and id attributes, maybe fieldsets/legends)
- [x] alt texts for all images
- [ ] each button has an icon (and some also a self-explanatory text)
- [x] there is a title in the head for every page
- [ ] check if h1, h2, h3 is used properly
- [ ] (optional: autocomplete in forms where suitable)
- [ ] check color contrast
