### ISSUE TITLE
US#17 - Improve UX of Create/Edit form

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#27]
## Value proposition
As a user
I want to have an improved UX in the create/edit form
so that I am less frustrated/irritated and enjoy submitting new projects more.

## Description
-

## Acceptance criteria
- [x] the short fact inputs for price category and difficulty are radio buttons
- [x] the user is informed if he/she forgot to enter a mandatory information via a error message
- [x] for the fields with multiple inputs (instruction steps, material and tools) each field can be deleted individually
- [x] next to the duration slider the current value is displayed (e.g. "8 hours")
- [x] when adding a new step/tool/material the new input field is focussed

## Tasks
- [x] implement error messages for mandatory inputs
- [x] change input type for price category and difficulty
- [x] add delete button for input field instructions, material and tools
- [x] show current value of input field next to the slider
