### ISSUE TITLE
US#16 - Color Coding based on category

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#28]
## Value proposition
As a user
I want the project cards in the overview to be colored according to their category
so that browsing through the app is more fun.

## Description

![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/8616b434-09b0-4160-acfb-b7a747fdad52)
![Bildschirmfoto 2024-02-02 um 16 13 50](https://github.com/On-Fi/D.I.Y-App/assets/29588302/a2e653e9-17f3-455d-8b28-60b203dca31f)
For every project in the overview and the favorites page the background of the card refers to the category of the project (garden, kitchen, home, bathroom or fashion).

## Acceptance criteria
- [ ] the project cards are colored according to their category (the image above shows which category matches which color)
- [ ] the colors are used consistently for every part of the app (overview, favorites etc.)
- [ ] Color coding is comply with accessibility standards, ensuring that information is still accessible to users with color vision deficiencies.

## Tasks
- [ ] write an object that matches each category with a color code
- [ ] make the background color of the Card Component a prop

**Comment by JessicaLoers** [comment]
**Hey D.I.Y.-APP Team ✌️**
**I really like the idea of your App.** 

Do I understand correctly that each project card is assigned to a specific category? And this category is visually represented by the respective colored bubble? 

For example, I can see a project in the overview like this:
_Homemade fruit basket made from straw.  (Dark gray bubble)_

If this is the case, I would strongly recommend that you adjust the wire frame in the description and completing the acceptance criteria. 

If not, this user story should be completely revised (including the value proposition), because as a developer on this ticket, I wouldn't know what to do.


**Example ACs:**
- Each project card has an associated category that is predefined in the system (bathroom, home, garden, kitchen, fashion)
- Colors are predefined and consistently assigned to each category. 
- The color coding is visible and consistent across all instances of project cards in the overview section, details page, .....  
- Color coding is comply with accessibility standards, ensuring that information is still accessible to users with color vision deficiencies.

**Comment by kristinwegener** [comment]
Thank you Jessica :) you're right, it wasn't very detailed and descriptive. We fixed that and will put it up for review again.
