### ISSUE TITLE
US#13-Loading Animation

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#29]
## Value proposition
As a user
I want to see a loading animation 
In order to distracte me from the loading time
## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/149980693/d7eb2fc6-14a0-4ad2-bb5c-508059aba7ee)
## Acceptance criteria
- [x] every time the app is loading the homepage for the first time the loading animation is displayed on the screen
- [x] every time the app is loading a card the loading animation is displayed on the screen
## Tasks
- [x] choose a SVG file
- [x] edit the code of the SVG file and make a component out of it
- [x] import the component everywhere it is needed
- [x] (optional: delay the fetcher function of the app)

**Comment by Roland-Hufnagel** [comment]
Looks good. 👍
