### ISSUE TITLE
US#03-Detail-Page

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#3]
## Value proposition
As a user
I want to visit a detail page for every project 
that shows all information including instructions 
and equipment 
In order to get more information about
the project and can start crafting.
## Description
![Image](https://github.com/On-Fi/DIY-App/assets/149980693/d24d42fa-5944-4fd8-bc98-9cb4722f0fce)
## Acceptance criteria
- [x] When I click on a project card in the overview
   I am redirected to the detail page of this project
- [x] The Detail Page contains a title, some short facts
  (such as time, money, category, difficulty), tools, material and instruction
## Tasks
- [x] create a Project Component
- [x] create Components for every Section of the Page
- [x] create [id]/index.js page
- [x] fetch data (with a GET-Request)
- [x] create the get route for single element

**Comment by F-Kirchhoff** [comment]
Hey DIY Team,
there is only one thing missing: creating the get route for single elements in your API! Add this to the tasks and you are good to go!
