### ISSUE TITLE
US#20 - Individual filters

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#30]
## Value proposition
As a user
I want to filter for only one category
so that it is easier to find results

## Description
Currently the filter only works when **all** filter categories are applied. This is not user friendly.

## Acceptance criteria
- [x] there is no filter button anymore
- [x] the filter is applied as soon as a new radio button is clicked or a new value inside the dropdown is clicked
- [x] the filters work individually (i can filter e.g. **only** for duration, not all at once)
- [x] there is a button to delete all filters

## Tasks
- [x] remove filter button
- [x] write new functions for each filter individually
- [x] add delete filter button

**Comment by Roland-Hufnagel** [comment]
Looks good, but a wireframe in the description would have helped me a lot.
