### ISSUE TITLE
US#21 - 404 page

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#31]
## Value proposition
As a user
when navigating to a project page that doesn't exist (anymore) I want to be informed via a 404 page
so that I am not irritated and can get back to the overview page easily

## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/3e7e4dab-196b-4ed8-ad88-3f5130b5dad0)

## Acceptance criteria
- [x] when opening a project detail page that doesn't exist (oder not anymore) I am redirected to a 404 page
- [x] the 404 page shows an image, explanatory text, a button back to the overview page and a project card
- [x] the displayed project card is a random project out of all existing projects in the database

## Tasks
- [x] create new page in pages folder
- [x] write a function that returns a random project
- [x] render image, text, button and the random project card
- [x] write logic that redirects the user to the 404 page when the project does not exist

**Comment by marcbendixen** [comment]
Good idea to include something like that 👍 
lgtm 🧑‍🚀
