### ISSUE TITLE
US#22 - Color Themes

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#32]
## Value proposition
As a user,
I want to choose a color theme that I like
In order to make my experience using the app more to my liking.
## Description
<img width="194" alt="Bildschirmfoto 2024-01-29 um 10 18 40" src="https://github.com/On-Fi/D.I.Y-App/assets/149980693/d8676da8-9f78-4cb2-9dc8-429f6b23c073">

## Acceptance criteria
- [ ] On the User Profile Page is the option displayed, to choose between four different color themes
- [ ] By clicking on one of the four color themes, the app changes it's color theme on all pages 
## Tasks
- [ ] Choose the colors for four different color themes
- [ ] Add a state to the app for the color themes
- [ ] Create a themes.js with an object inside, that contains all of the colors for the CSS
- [ ] Edit the colors inside the styled-components from hard coded to soft coded
