### ISSUE TITLE
US#23 - Knowledge section

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#33]
## Value proposition
As a user
I want to find some background information regarding crafting/DIY,
to get a deeper understand of topics.

## Description

![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/3646a820-ccc2-4841-a477-8cd5f5f8d701)

## Acceptance criteria
- [x] There's a page /knowledge which lists all existing knowledge articles in an overview
- [x] each article previews an image, title and a short teaser.
- [x] in the navigation bar there's a new item linking to the knowledge section (e.g. book-icon)

## Tasks
- [x] set up the /knowledge page
- [x] write knowledge articles (ChatGPT)
- [x] save new data for every article (not MongoDB, save it in a new file inside the project)
- [x] create ArticleCard Component and render it on the page
- [x] add link in the navigation bar
