### ISSUE TITLE
US#24 -  Knowledge articles

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#34]
## Value proposition
As a user
i want to have some background information regarding crafting/DIY
to improve my skills

## Description

![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/0ac3c0f0-ed57-4922-a372-f803ae185d0f)

## Acceptance criteria
- [x] theres a detail page for every article that shows the content for this article (image, headline, text)
- [x] the link for the details pages is /knowledge/[slug]
- [x] there's a button to get back to all articles 

## Tasks
- [x] add slugs for each article in the data
- [x] set up a new page /knowledge/[slug]
- [x] import useRouter
- [x] (if necessary) write new components
