### ISSUE TITLE
US#25 - Link projects in Articles

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#35]
## Value proposition
As a user
I want to be informed about related projects when reading an article
to be inspired and to get suitable ideas for my topic.

## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/ecad96bd-ea63-4610-809f-d06ebcea4c67)

## Acceptance criteria
- [x] below every article there are projects that are related to the topic of the article 
- [x] by clicking on the project card the user is redirected to the project detail page

## Tasks
- [ ] every article gets some keywords in the database (e.g. "wood", "textile" etc.)
- [ ] write a function that looks through all projects and searches for that keyword in the title or description of the project
- [ ] render card component for these projects below the article
