### ISSUE TITLE
US#04-Favorites

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#4]
## Value proposition
As a user
I want to mark projects as favorites
In order to get a good overview over my favorite projects.
## Description
![Image](https://github.com/On-Fi/DIY-App/assets/149980693/c345e7e4-2270-4f88-ab97-90c4a8421fc7)
![Image 2](https://github.com/On-Fi/D.I.Y-App/assets/29588302/12da8b4d-d50f-4811-a54f-81b7d1d06b4d)
## Acceptance criteria
- [x] On every project card in the overview (and on every detail page) there is a heart-icon
- [x] When clicking this heart icon I mark this project as one of my favorites
- [x] When click the heart icon again i unmark this project as one of my favorites
- [x] after marking a project as favorites it appears on my favorites list, after unmarking it it disappears from the list
- [x] I get to my favorites list by clicking on the User Tab in the navigation
- [x] the favorites remain visible even after reloading the page
## Tasks
- [x] create State for Favorites
- [x] save the state of favorites in the local storage of the client
- [x] create a heart icon component
- [x] integrate a Icon/SVG and implement it in the heart icon component
- [x] implement a toggle function for the heart icon
- [x] create a Favorites page
- [x] create a link to the favorites page

**Comment by MartaJaekel** [comment]
Hello Team , nice User Story ! For the value proposition i think that the need is more to have the favorites collected in one place to have a good overview of them  rather than remembering them .There is also  a point missing in the acceptance criteria  . I think you should add what happens when the user clicks on the heart icon again. I guess that then project disappears from the favorites list.
Also you could extend a bit more the tasks providing them with more details, like creating a link to the corresponding favorites page , implementing the icon in the Navbar, adding a toggle function for the heart icon . Also you might consider to create a component for the favorite button to make it more reusable.

**Comment by mbosselmann** [comment]
Hi Team D.I.Y-App,
good job! 👍 I have some additional remarks for you to consider:

**Description/ Acceptance Criteria:**
- "On every project card in the overview (and on every detail page) there is a heart-icon" -> You describe that the heart icon is also displayed on the details page. It would be nice to see a wireframe for the details page to illustrate this. :)
- as you mentioned local storage in your tasks, you can add as criterion that the favorites should still be visible after reloading the page.

**Tasks:**
- "set up a Local Storage" - if we want to describe it more correct you do not want to set up a local storage as a local storage is part of each browser, you want to work with local storage to store the favorites there. :)

I hope this helps to improve your user story further! 💪

**Comment by CJAkkuec** [comment]
Almost!

Now you only need to add what @mbosselmann pointed out to your developer tasks.
Something like
> Store the `favorites` state in the client's local storage

or similar, depending on how you're going to handle your data.
