### ISSUE TITLE
US#26 - Link articles in projects

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#40]
## Value proposition
As a user
I want to be informed about related articles when looking at a DIY project
to get more general knowledge of crafting.

## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/b73b537f-99df-4798-a140-64708a48f3ec)

## Acceptance criteria
- [ ] below every project there are articles that are related to the topic of the project 
- [ ] by clicking on the article card the user is redirected to the article

## Tasks
- [ ] write a function that looks through all articles and searches for equality with one of the keywords
- [ ] render article card component for these articles below the project
