### ISSUE TITLE
US#27 - Various improvements

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#48]
## Value proposition
As a user,
I want a consistent design and behavior
so that the overall user experience corresponds to my expectations.

## Acceptance Criteria
- [ ] the heart icon which is used for the favorite feature is red
- [x] the loading spinner that appears when data is loading fits the theme (looks like a worm or similar)
- [x] the logo in the header is clickable and leads to the overview page

## Tasks
- [x] color favorite button (heart icon) red
- [x] insert new spinner (worm gif)
- [x] make logo in header clickable and lead to homepage
- [x] remove yellow background on logged-out plus icon
- [x] add a CredentialsProvider in the [...nextauth].js

**Comment by JessicaLoers** [comment]
**Hi @kristinwegener** ✨
I've some suggestions to improve the US story. 

The actual reason for this user story is to improve the UX and you can actually formulate this in the value proposition.

**As a user**,
**I want** a consistent design and behavior 
**so that** the overall user experience corresponds to my expectations.

**Acceptance Criteria**
 - the heart icon is red
 _note: Which icon is meant, a precise formulation is necessary here_
 - the loading spinner fits the theme (woodworm)
  _note: Which icon is meant, a precise formulation is necessary here_
-  the logo in the header is clickable
_note:  What happens when I click on the logo? Will I be redirected to another page, if so which one is it?_

**A wireframe could also provide clarity.**
