### ISSUE TITLE
US#05-Filter

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#5]
## Value proposition
As a user
I want to filter the overview page
In order to find projects faster and easier
## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/081d2437-b545-4ccc-b031-00f539f02af3)
## Acceptance criteria
- [x] On the overview page and the favorite page, 

  above the project cards there is a filter area
- [x] I can filter for price category, difficulty level, 
  category and duration
- [x] The filter criteria is applied as soon as I click on "filter"
- [x] The list of project cards then only shows projects that 
  match my filter criteria 
## Tasks
- [x] create a FilterSection Component
- [x] set up filters that filter data based on a category
- [x] create a filter button that triggers the filter function
- [x] implement derived state for filter

**Comment by CJAkkuec** [comment]
>  The filter criteria is applied as soon as I click on "filter"

Strictly speaking, the wireframe says "filtern", but I'm not going to ask you to change that - unless you want to. Usually I'd probably make sure that I stick to one language, though this might just as well have been just a tiny oversight.

>  create a Filterarea Component

I'd probably call that a FilterSection, but that's just a preference of mine.

> create a new API endpoint for filtered projects

I'd advise very strongly against this for the following reasons:
- If you're already fetching all projects on load, then you need only filter over the data you already have in state
- If you fetch data every time the user clicks on filter, the overall traffic is going to skyrocket

So all you need is to work with derived states (and perhaps a switch case).

(Verbose/Incomplete) Example:
```js
const [values, setValue] = useState(initialValues);
const [filterKeyword, setFilterKeyword] = useState("")

const stateFilteredByShortDuration = values.filter(value => value.time < 60);
const stateFilteredByLongDuration = values.filter(value => value.time > 60);
const stateFilteredBySomething = values.filter(value => value.something);

// Conditional Rendering with filterKeyword, etc
```

By the way, I'd probably suggest checkboxes rather than radio buttons, unless you want to allow your user to only ever filter by one category at the same time.
