### ISSUE TITLE
US#28 - Responsive Design

### ISSUE THREAD

**Issue by kristinwegener** [On-Fi/D.I.Y-App#57]
## Value proposition
As a user
I want to have a responsive design
so that I can also enjoy the app when I am using the desktop view

## Acceptance criteria
- [ ] on the desktop view the cards on the homepage are displayed in a grid view (2 or 3 cards next to each other)
- [ ] the filter area is on the left side

## Tasks
- [ ] add media query to project list component
- [ ] style flexbox differently based on viewport size
