### ISSUE TITLE
US#06-Searchbar

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#6]
## Value proposition
As a user
I want to search for certain search terms
In order to find specific projects faster and easier
## Description
![Image](https://github.com/On-Fi/DIY-App/assets/149980693/c5f7ac85-09b0-4ed1-966b-306b967be1d1)
## Acceptance criteria
- [x] On the overview page above the filter area there is a search bar
- [x] I can type text into the search bar and when clicking the search button this search term is applied
## Tasks
- [x] create a searchbar component
- [x] add the searchbar component to the overview page
- [x] set up a filter function that filters the displayed project cards based on user inputs (search term)

**Comment by MaikBerdelmann** [comment]
Nicely done, looks good to me :)
