### ISSUE TITLE
US#07-Edit-Projects

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#7]
## Value proposition
As a user
I want to edit existing projects
In order to update information, fix typos etc.
## Description
![Image](https://github.com/On-Fi/D.I.Y-App/assets/29588302/924ef72d-5550-4ed1-b5ba-e8ad981c3a79)

## Acceptance criteria
- [x] On the detail page of every project there is a button "Edit project"
- [x] When clicking this button the Edit Form opens
- [x] The Edit Form is equal to the create form, but it already contains all the project information
- [x] Clicking the button "Save Changes" saves the data and redirects the user to the detail page
- [x] Clicking the button "Cancel Changes" stops the editing process and redirects the user to the detail page

## Tasks
- [x] set up [id]/edit page 
- [x] add a edit button to detail page that redirects the user to the edit page
- [x] make the Form Component reusable for every Project
- [x] set up PUT/PATCH Request in api folder
- [x] set up a submit handler trigger PUT/PATCH Request

**Comment by MartaJaekel** [comment]
Hey, looks nice ! I just noticed that the create form and so also the edit form doesn't have the same structure of the one in the create project use story. For the tasks you could implement the fact that you need to create an edit and a cancel button.
Otherwise looks fine to me :)

**Comment by Hendrik-Pils** [comment]
The user story is very good. Fine!
