### ISSUE TITLE
US#08-User-Login

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/D.I.Y-App#8]
## Value proposition
As a user
I want only logged-in users to be able to submit ideas
so that the quality of the content is better.

## Acceptance criteria
- [x] the buttons for editing & deleting are only displayed for logged-in users (for **all** logged-in users, doesn't matter if he/she was the one creating it, that will be done in a later user story)
- [x] the button create is displayed to not-logged-in users, but clicking it redirects the user to the login-form
- [x] there is a log-out-button on the homepage below the projects (or a login-button when user is not logged-in)

## Tasks
- [x] Create O-Auth in GitHub Account
- [x] setup next-auth and login
- [x] create new page for login
- [x] create login/logout button on bottom of the overview page (make login-button redirect to login page)
- [x] hide edit/delete buttons in the frontend so that only logged-in users see them
- [x] save edit and create form in the frontend so that only logged-in users can open them
- [x] save the api routes creating/editing/deleting in the backend

**Comment by Roland-Hufnagel** [comment]
Hi. Your story is a good idea. But please apply some changes:
Please write a userstory instead of a developerstory. I'm sure you find some good values for a user.
Please define a bit more precise Acceptance Criterias: You mention a logout-button but not a login button. Is it possible for logged in users to delete other users projects?...
You can be a bit more precise in the tasks as well: Do you want a login component? Where is it rendered?
